import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "@/styles/layout.module.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta charSet="utf-8" />
      <Head>
          <link rel="icon" href="./favicon.ico" />
      </Head>
      <title>HUMAN IMPACT</title>
      <body className={inter.className} style={{margin: 0}}>
        {children}
      </body>
    </html>
  );
}
